"""initial

Revision ID: ba03f690aca4
Revises: 
Create Date: 2026-04-03 05:21:38.783891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba03f690aca4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fude_polygons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('polygon_uuid', sa.String(length=64), nullable=False),
    sa.Column('land_type', sa.Integer(), nullable=True),
    sa.Column('issue_year', sa.Integer(), nullable=True),
    sa.Column('edit_year', sa.Integer(), nullable=True),
    sa.Column('history', sa.String(length=512), nullable=True),
    sa.Column('last_polygon_uuid', sa.String(length=64), nullable=True),
    sa.Column('prev_last_polygon_uuid', sa.String(length=64), nullable=True),
    sa.Column('local_government_cd', sa.String(length=32), nullable=True),
    sa.Column('point_lng', sa.Float(), nullable=True),
    sa.Column('point_lat', sa.Float(), nullable=True),
    sa.Column('old_polygon_id', sa.String(length=64), nullable=True),
    sa.Column('pref_id', sa.String(length=2), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fude_polygons_local_government_cd'), 'fude_polygons', ['local_government_cd'], unique=False)
    op.create_index(op.f('ix_fude_polygons_polygon_uuid'), 'fude_polygons', ['polygon_uuid'], unique=True)
    op.create_index(op.f('ix_fude_polygons_pref_id'), 'fude_polygons', ['pref_id'], unique=False)
    op.create_table('gsmap_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('grid_id', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('start_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('end_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('hit_hours', sa.Integer(), nullable=False),
    sa.Column('max_gauge_mm_h', sa.Float(), nullable=False),
    sa.Column('sum_gauge_mm_h', sa.Float(), nullable=False),
    sa.Column('mean_gauge_mm_h', sa.Float(), nullable=False),
    sa.Column('threshold_mm_h', sa.Float(), nullable=False),
    sa.Column('repr_source_file', sa.String(length=255), nullable=True),
    sa.Column('rainfall_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsmap_events_end_ts_utc'), 'gsmap_events', ['end_ts_utc'], unique=False)
    op.create_index(op.f('ix_gsmap_events_grid_id'), 'gsmap_events', ['grid_id'], unique=False)
    op.create_index(op.f('ix_gsmap_events_id'), 'gsmap_events', ['id'], unique=False)
    op.create_index(op.f('ix_gsmap_events_lat'), 'gsmap_events', ['lat'], unique=False)
    op.create_index(op.f('ix_gsmap_events_lon'), 'gsmap_events', ['lon'], unique=False)
    op.create_index(op.f('ix_gsmap_events_region'), 'gsmap_events', ['region'], unique=False)
    op.create_index(op.f('ix_gsmap_events_start_ts_utc'), 'gsmap_events', ['start_ts_utc'], unique=False)
    op.create_table('gsmap_grids',
    sa.Column('grid_id', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('is_japan_land', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('grid_id')
    )
    op.create_table('gsmap_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts_utc', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('gauge_mm_h', sa.Float(), nullable=False),
    sa.Column('rain_mm_h', sa.Float(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('grid_id', sa.String(length=32), nullable=True),
    sa.Column('source_file', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsmap_points_ts_utc'), 'gsmap_points', ['ts_utc'], unique=False)
    op.create_table('japan_grids',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grid_id', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('is_rice_paddy', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_highway', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_japan_grids_grid_id'), 'japan_grids', ['grid_id'], unique=True)
    op.create_table('road_polygons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('n13_001', sa.String(length=32), nullable=True),
    sa.Column('n13_002', sa.String(length=32), nullable=True),
    sa.Column('n13_003', sa.String(length=32), nullable=True),
    sa.Column('n13_004', sa.String(length=32), nullable=True),
    sa.Column('n13_005', sa.Integer(), nullable=True),
    sa.Column('n13_006', sa.String(length=32), nullable=True),
    sa.Column('n13_007', sa.String(length=32), nullable=True),
    sa.Column('n13_008', sa.String(length=32), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_polygons_n13_006'), 'road_polygons', ['n13_006'], unique=False)
    op.create_table('s1_pairs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grid_id', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('event_start_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('event_end_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('threshold_mm_h', sa.Float(), nullable=False),
    sa.Column('hit_hours', sa.Integer(), nullable=False),
    sa.Column('max_gauge_mm_h', sa.Float(), nullable=False),
    sa.Column('after_scene_id', sa.String(length=128), nullable=False),
    sa.Column('after_platform', sa.String(length=16), nullable=True),
    sa.Column('after_mission', sa.String(length=8), nullable=True),
    sa.Column('after_pass_direction', sa.String(length=8), nullable=True),
    sa.Column('after_relative_orbit', sa.Integer(), nullable=True),
    sa.Column('after_start_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('after_end_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('before_scene_id', sa.String(length=128), nullable=True),
    sa.Column('before_start_ts_utc', sa.DateTime(), nullable=True),
    sa.Column('before_end_ts_utc', sa.DateTime(), nullable=True),
    sa.Column('before_relative_orbit', sa.Integer(), nullable=True),
    sa.Column('delay_h', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s1_pairs_after_scene_id'), 's1_pairs', ['after_scene_id'], unique=False)
    op.create_index(op.f('ix_s1_pairs_before_scene_id'), 's1_pairs', ['before_scene_id'], unique=False)
    op.create_index(op.f('ix_s1_pairs_event_start_ts_utc'), 's1_pairs', ['event_start_ts_utc'], unique=False)
    op.create_index(op.f('ix_s1_pairs_grid_id'), 's1_pairs', ['grid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_s1_pairs_grid_id'), table_name='s1_pairs')
    op.drop_index(op.f('ix_s1_pairs_event_start_ts_utc'), table_name='s1_pairs')
    op.drop_index(op.f('ix_s1_pairs_before_scene_id'), table_name='s1_pairs')
    op.drop_index(op.f('ix_s1_pairs_after_scene_id'), table_name='s1_pairs')
    op.drop_table('s1_pairs')
    op.drop_index(op.f('ix_road_polygons_n13_006'), table_name='road_polygons')
    op.drop_table('road_polygons')
    op.drop_index(op.f('ix_japan_grids_grid_id'), table_name='japan_grids')
    op.drop_table('japan_grids')
    op.drop_index(op.f('ix_gsmap_points_ts_utc'), table_name='gsmap_points')
    op.drop_table('gsmap_points')
    op.drop_table('gsmap_grids')
    op.drop_index(op.f('ix_gsmap_events_start_ts_utc'), table_name='gsmap_events')
    op.drop_index(op.f('ix_gsmap_events_region'), table_name='gsmap_events')
    op.drop_index(op.f('ix_gsmap_events_lon'), table_name='gsmap_events')
    op.drop_index(op.f('ix_gsmap_events_lat'), table_name='gsmap_events')
    op.drop_index(op.f('ix_gsmap_events_id'), table_name='gsmap_events')
    op.drop_index(op.f('ix_gsmap_events_grid_id'), table_name='gsmap_events')
    op.drop_index(op.f('ix_gsmap_events_end_ts_utc'), table_name='gsmap_events')
    op.drop_table('gsmap_events')
    op.drop_index(op.f('ix_fude_polygons_pref_id'), table_name='fude_polygons')
    op.drop_index(op.f('ix_fude_polygons_polygon_uuid'), table_name='fude_polygons')
    op.drop_index(op.f('ix_fude_polygons_local_government_cd'), table_name='fude_polygons')
    op.drop_table('fude_polygons')
    # ### end Alembic commands ###
