"""create gsmap tables

Revision ID: fde62d2349f8
Revises: 
Create Date: 2025-11-15 20:04:33.857746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde62d2349f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsmap_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts_utc', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('gauge_mm_h', sa.Float(), nullable=False),
    sa.Column('rain_mm_h', sa.Float(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('grid_id', sa.String(length=32), nullable=True),
    sa.Column('source_file', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsmap_points_ts_utc'), 'gsmap_points', ['ts_utc'], unique=False)
    op.create_table('rain_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts_utc', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('gauge_mm_h', sa.Float(), nullable=False),
    sa.Column('grid_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Enum('rain10_30', 'clear0', name='rain_event_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rain_events_ts_utc'), 'rain_events', ['ts_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rain_events_ts_utc'), table_name='rain_events')
    op.drop_table('rain_events')
    op.drop_index(op.f('ix_gsmap_points_ts_utc'), table_name='gsmap_points')
    op.drop_table('gsmap_points')
    # ### end Alembic commands ###
